{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 181,
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "from torch import nn\n",
    "from src.data import get_data\n",
    "from src.models import get_encoder, get_decoder\n",
    "from src.utils import softclip\n",
    "from src.hessian import laplace\n",
    "import yaml\n",
    "from copy import deepcopy\n",
    "from torch.nn.utils import parameters_to_vector, vector_to_parameters\n",
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "from sklearn.model_selection import GridSearchCV\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "import os\n",
    "import warnings\n",
    "from tqdm import tqdm\n",
    "\n",
    "def get_model(encoder, decoder):\n",
    "    \n",
    "    net = deepcopy(encoder.encoder._modules)\n",
    "    decoder = decoder.decoder._modules\n",
    "    max_ = max([int(i) for i in net.keys()])\n",
    "    for i in decoder.keys():\n",
    "        net.update({f\"{max_+int(i) + 1}\": decoder[i]})\n",
    "\n",
    "    return nn.Sequential(net)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Load checkpoints for the different models"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 182,
   "metadata": {},
   "outputs": [],
   "source": [
    "path_ae = \"../weights/celeba/[no_conv_False]_[use_var_decoder_False]_\"\n",
    "with open(f\"{path_ae}/config.yaml\") as file:\n",
    "    config = yaml.full_load(file)\n",
    "ae_encoder = get_encoder(config, latent_size=config['latent_size'])\n",
    "ae_encoder.load_state_dict(torch.load(f\"{path_ae}/encoder.pth\"))\n",
    "ae_encoder.eval()\n",
    "\n",
    "path_mcae = \"../weights/celeba/mcdropout_ae/[no_conv_False]_[dropout_rate_0.2]_[use_var_decoder_False]_\"\n",
    "with open(f\"{path_mcae}/config.yaml\") as file:\n",
    "    config = yaml.full_load(file)\n",
    "mcae_encoder = get_encoder(config, latent_size=config['latent_size'], dropout=config[\"dropout_rate\"])\n",
    "mcae_encoder.load_state_dict(torch.load(f\"{path_mcae}/encoder.pth\"))\n",
    "\n",
    "path_vae = \"../weights/celeba/vae_[use_var_dec=False]/[no_conv_False]_[use_var_decoder_False]_\"\n",
    "with open(f\"{path_vae}/config.yaml\") as file:\n",
    "    config = yaml.full_load(file)\n",
    "vae_encoder_mu = get_encoder(config, latent_size=config['latent_size'])\n",
    "vae_encoder_mu.load_state_dict(torch.load(f\"{path_vae}/mu_encoder.pth\"))\n",
    "vae_encoder_var = get_encoder(config, latent_size=config['latent_size'])\n",
    "vae_encoder_var.load_state_dict(torch.load(f\"{path_vae}/var_encoder.pth\"))\n",
    "\n",
    "path_lae= \"../weights/celeba/[backend_layer]_[approximation_mix]_[no_conv_False]_[train_samples_1]_/[backend_layer]_[approximation_mix]_[no_conv_False]_[train_samples_1]_\"\n",
    "with open(f\"{path_lae}/config.yaml\") as file:\n",
    "    config = yaml.full_load(file)\n",
    "lae_encoder = get_encoder(config, latent_size=config['latent_size'])\n",
    "lae_decoder = get_decoder(config, latent_size=config['latent_size'])\n",
    "lae_net = get_model(lae_encoder, lae_decoder).eval()\n",
    "lae_net.load_state_dict(torch.load(f\"{path_lae}/net.pth\"))\n",
    "mu_q = parameters_to_vector(lae_net.parameters()).cuda()\n",
    "l = laplace.DiagLaplace()\n",
    "h = torch.load(f\"{path_lae}/hessian.pth\").cpu()\n",
    "sigma_q = l.posterior_scale(h).cuda()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Construct function for loading subset of validation data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 183,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "torch.Size([352, 3, 64, 64])\n",
      "torch.Size([352, 40])\n",
      "torch.Size([5, 3, 64, 64])\n",
      "torch.Size([5, 40])\n",
      "torch.Size([347, 3, 64, 64])\n",
      "torch.Size([347, 40])\n"
     ]
    }
   ],
   "source": [
    "_, val_dataloader = get_data(\"celeba\")\n",
    "images, labels = [ ], [ ]\n",
    "\n",
    "for batch_idx, batch in enumerate(val_dataloader):\n",
    "    if batch_idx > 10:\n",
    "        break\n",
    "    x, y = batch\n",
    "    images.append(x)\n",
    "    labels.append(y)\n",
    "images = torch.cat(images, 0)\n",
    "labels = torch.cat(labels, 0)\n",
    "\n",
    "print(images.shape)\n",
    "print(labels.shape)\n",
    "\n",
    "def get_dataset(n_select):\n",
    "    idx = torch.randperm(images.shape[0])\n",
    "    return images[idx[:n_select]], labels[idx[:n_select]], images[idx[n_select:]], labels[idx[n_select:]]\n",
    "\n",
    "selected_images, selected_labels, eval_set_images, eval_set_labels = get_dataset(5)\n",
    "print(selected_images.shape)\n",
    "print(selected_labels.shape)\n",
    "print(eval_set_images.shape)\n",
    "print(eval_set_labels.shape)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Construct functions for embedding data into representation space for the different models"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 184,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "standard ae\n",
      "torch.Size([1, 128])\n",
      "monte-carlo ae\n",
      "torch.Size([2, 128])\n",
      "vae\n",
      "torch.Size([2, 128])\n",
      "lae\n",
      "torch.Size([2, 128])\n"
     ]
    }
   ],
   "source": [
    "def get_encoding_ae(data, n=1):\n",
    "    return ae_encoder(data)\n",
    "\n",
    "print('standard ae')\n",
    "print(get_encoding_ae(images[:1], n=2).shape)\n",
    "\n",
    "def get_encoding_mcae(data, n=1):\n",
    "    return torch.cat([mcae_encoder(data) for _ in range(n)], 0)\n",
    "\n",
    "print('monte-carlo ae')\n",
    "print(get_encoding_mcae(images[:1], n=2).shape)\n",
    "\n",
    "def get_encoding_vae(data, n=1):\n",
    "    mu = vae_encoder_mu(data)\n",
    "    sigma = torch.exp(softclip(vae_encoder_var(data), min=-3))\n",
    "    return torch.cat([mu + torch.randn_like(sigma) * sigma for _ in range(n)])\n",
    "\n",
    "print('vae')\n",
    "print(get_encoding_vae(images[:1], n=2).shape)\n",
    "\n",
    "def sample():\n",
    "    return (mu_q + torch.randn_like(sigma_q) * sigma_q).cpu()\n",
    "    \n",
    "def get_encoding_lae(data, n=1):\n",
    "    embeddings = [ ]\n",
    "    def fw_hook_get_latent(module, input, output):\n",
    "        embeddings.append(output.detach().cpu())\n",
    "    hook = lae_net[20].register_forward_hook(fw_hook_get_latent)\n",
    "\n",
    "    if n == 1:\n",
    "        _ = lae_net(data)\n",
    "        hook.remove()\n",
    "        return embeddings[0]\n",
    "\n",
    "    for i in range(n):\n",
    "        vector_to_parameters(sample(), lae_net.parameters())\n",
    "        _ = lae_net(data)\n",
    "    hook.remove()\n",
    "    return torch.cat(embeddings, 0)\n",
    "\n",
    "print('lae')\n",
    "print(get_encoding_lae(images[:1], n=2).shape)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Run experiment"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 185,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0 0 0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 6\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 6\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 7\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 7\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 8\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 8\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 9\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 9\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 10\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 10\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_search.py:969: UserWarning: One or more of the test scores are non-finite: [ 0.  0.  0.  0.  0. nan nan nan nan nan]\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0 0 1\n",
      "0 0 2\n",
      "0 0 3\n",
      "1 0 0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 6\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 6\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 7\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 7\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 8\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 8\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 9\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 9\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 10\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 10\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_search.py:969: UserWarning: One or more of the test scores are non-finite: [ 0.  0.  0.  0.  0. nan nan nan nan nan]\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1 0 1\n",
      "1 0 2\n",
      "1 0 3\n",
      "2 0 0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 6\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 6\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 7\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 7\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 8\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 8\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 9\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 9\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 10\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 10\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_search.py:969: UserWarning: One or more of the test scores are non-finite: [ 0.  0.  0.  0.  0. nan nan nan nan nan]\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2 0 1\n",
      "2 0 2\n",
      "2 0 3\n",
      "3 0 0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 6\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 6\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 7\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 7\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 8\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 8\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 9\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 9\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 10\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 10\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_search.py:969: UserWarning: One or more of the test scores are non-finite: [ 0.  0.  0.  0.  0. nan nan nan nan nan]\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "3 0 1\n",
      "3 0 2\n",
      "3 0 3\n",
      "4 0 0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 6\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 6\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 7\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 7\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 8\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 8\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 9\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 9\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 10\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 418, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\base.py\", line 651, in score\n",
      "    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 214, in predict\n",
      "    neigh_dist, neigh_ind = self.kneighbors(X)\n",
      "  File \"c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 727, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 10\n",
      "\n",
      "  warnings.warn(\n",
      "c:\\Users\\nsde\\Anaconda3\\envs\\laplace\\lib\\site-packages\\sklearn\\model_selection\\_search.py:969: UserWarning: One or more of the test scores are non-finite: [ 0.  0.  0.  0.  0. nan nan nan nan nan]\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "4 0 1\n",
      "4 0 2\n",
      "4 0 3\n"
     ]
    }
   ],
   "source": [
    "with torch.inference_mode():\n",
    "    scale_factor = 100\n",
    "    names = ['ae', 'mcae', 'vae', 'lae']\n",
    "    label_size = [10]\n",
    "    reps = 5\n",
    "\n",
    "    res = np.zeros((reps, len(label_size), len(names), 40))\n",
    "    for r in range(reps):\n",
    "        for j, (name, encoder) in enumerate(zip(names, [get_encoding_ae, get_encoding_mcae, get_encoding_vae, get_encoding_lae])):\n",
    "            for i, n_select in enumerate(label_size):\n",
    "                print(r,i,j)\n",
    "                selected_images, selected_labels, eval_set_images, eval_set_labels = get_dataset(n_select)\n",
    "                eval_data = torch.cat([encoder(d.unsqueeze(0)) for d in eval_set_images], 0)\n",
    "                train_data = torch.cat([encoder(d.unsqueeze(0), scale_factor) for d in selected_images], 0)\n",
    "                train_labels = selected_labels.repeat_interleave(scale_factor, 0) if name != 'ae' else selected_labels\n",
    "                with warnings.catch_warnings():\n",
    "                    warnings.filterwarnings(\"ignore\")\n",
    "                    classifier = GridSearchCV(\n",
    "                        KNeighborsClassifier(),\n",
    "                        {'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]},\n",
    "                        cv=2,\n",
    "                        refit=True,\n",
    "                    )\n",
    "                classifier.fit(train_data.detach().numpy(), train_labels.detach().numpy())\n",
    "                preds = classifier.predict(eval_data.detach().numpy())\n",
    "                acc = (preds == eval_set_labels.numpy()).mean(axis=0)\n",
    "                res[r,i,j,:] = acc"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Extract overall accuracy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 191,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(5, 1, 4, 40)\n",
      "(5, 4, 40)\n",
      "(4, 40)\n",
      "[0.75492203 0.74271442 0.73564815 0.74064327]\n",
      "[0.7379386  0.72457602 0.73108187 0.74064327]\n"
     ]
    }
   ],
   "source": [
    "np.save('results_celeba_all.npy', res)\n",
    "print(res.shape)\n",
    "print(res.mean(0).mean(-1))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Per label accuracy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 195,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "                            0         1         2         3\n",
      "5_o_Clock_Shadow     0.872320  0.754386  0.860624  0.795906\n",
      "Arched_Eyebrows      0.506823  0.521442  0.549708  0.605848\n",
      "Attractive           0.515595  0.500975  0.499025  0.536842\n",
      "Bags_Under_Eyes      0.797271  0.699805  0.752437  0.682456\n",
      "Bald                 0.985380  0.985380  0.985380  0.985380\n",
      "Bangs                0.815789  0.827485  0.800195  0.801754\n",
      "Big_Lips             0.607212  0.449318  0.524366  0.550292\n",
      "Big_Nose             0.676413  0.769981  0.701754  0.633333\n",
      "Black_Hair           0.680312  0.650097  0.581871  0.605263\n",
      "Blond_Hair           0.804094  0.857700  0.793372  0.728070\n",
      "Blurry               0.949318  0.950292  0.935673  0.943860\n",
      "Brown_Hair           0.616959  0.636452  0.713450  0.577778\n",
      "Bushy_Eyebrows       0.819688  0.751462  0.804094  0.783041\n",
      "Chubby               0.883041  0.923977  0.846004  0.912865\n",
      "Double_Chin          0.944444  0.897661  0.886940  0.873099\n",
      "Eyeglasses           0.885965  0.899610  0.886940  0.848538\n",
      "Goatee               0.955166  0.956140  0.897661  0.956140\n",
      "Gray_Hair            0.973684  0.973684  0.973684  0.969006\n",
      "Heavy_Makeup         0.454191  0.523392  0.495127  0.569591\n",
      "High_Cheekbones      0.499025  0.486355  0.494152  0.514035\n",
      "Male                 0.607212  0.537037  0.543860  0.557310\n",
      "Mouth_Slightly_Open  0.533138  0.468811  0.487329  0.514620\n",
      "Mustache             0.963938  0.887914  0.964912  0.963743\n",
      "Narrow_Eyes          0.850877  0.837232  0.751462  0.820468\n",
      "No_Beard             0.863548  0.761209  0.764133  0.853801\n",
      "Oval_Face            0.589669  0.660819  0.655945  0.580702\n",
      "Pale_Skin            0.967836  0.955166  0.949318  0.969591\n",
      "Pointy_Nose          0.626706  0.508772  0.632554  0.626316\n",
      "Receding_Hairline    0.907407  0.911306  0.844055  0.912281\n",
      "Rosy_Cheeks          0.801170  0.874269  0.857700  0.860819\n",
      "Sideburns            0.959064  0.961988  0.889864  0.961988\n",
      "Smiling              0.533138  0.492203  0.513645  0.525731\n",
      "Straight_Hair        0.712476  0.724172  0.654971  0.589474\n",
      "Wavy_Hair            0.571150  0.487329  0.531189  0.524561\n",
      "Wearing_Earrings     0.617934  0.731969  0.654971  0.620468\n",
      "Wearing_Hat          0.955166  0.953216  0.956140  0.953801\n",
      "Wearing_Lipstick     0.525341  0.497076  0.498051  0.540351\n",
      "Wearing_Necklace     0.682261  0.834308  0.754386  0.756725\n",
      "Wearing_Necktie      0.944444  0.874269  0.876218  0.932749\n",
      "Young                0.741715  0.733918  0.662768  0.687135\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "csv_file = pd.read_csv(\"../data/celeba/list_attr_celeba.txt\", index_col=0)\n",
    "list(csv_file.keys())[1:]\n",
    "df=pd.DataFrame(data=res, columns=list(csv_file.keys())[1:])\n",
    "print(df.T)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "06eb188f80c73fa6401bc2353cb283ae3bb523fbce23a94b0a24eb0ce551d284"
  },
  "kernelspec": {
   "display_name": "Python 3.9.12 ('laplace')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
